# Generated by Django 4.2.7 on 2023-12-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
        ("crowd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowd",
            name="persons",
            field=models.ManyToManyField(related_name="crowds", to="person.person"),
        ),
    ]
