# Generated by Django 4.2.7 on 2023-12-02 22:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="access_failed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="concurrency_stamp",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="lockout_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="lockout_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="password_hash",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=32, region=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="phone_number_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="security_stamp",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
