# Generated by Django 4.2.7 on 2023-12-03 01:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_person_access_failed_count_person_concurrency_stamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="access_failed_count",
        ),
        migrations.RemoveField(
            model_name="person",
            name="concurrency_stamp",
        ),
        migrations.RemoveField(
            model_name="person",
            name="lockout_enabled",
        ),
        migrations.RemoveField(
            model_name="person",
            name="lockout_end",
        ),
        migrations.RemoveField(
            model_name="person",
            name="password_hash",
        ),
        migrations.RemoveField(
            model_name="person",
            name="security_stamp",
        ),
        migrations.RemoveField(
            model_name="person",
            name="two_factor_enabled",
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
