# Generated by Django 4.2.7 on 2023-11-30 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_crowd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowd",
            name="address",
        ),
    ]
