# Generated by Django 4.2.7 on 2023-12-03 01:17

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("person", "0003_remove_person_access_failed_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=address.models.AddressField(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="address.address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
    ]
