# Generated by Django 4.2.7 on 2023-12-03 01:24

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("person", "0004_alter_person_address_alter_person_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="address",
            field=address.models.AddressField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="address.address",
            ),
        ),
    ]
