# Generated by Django 4.2.7 on 2023-12-12 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crowd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "crowd_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="crowd.crowd",
                    ),
                ),
                (
                    "crowds",
                    models.ManyToManyField(related_name="churches", to="crowd.crowd"),
                ),
            ],
            options={
                "verbose_name_plural": "churches",
            },
            bases=("crowd.crowd",),
        ),
    ]
