# Generated by Django 4.2.7 on 2023-12-02 16:09

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "crowd_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="person.crowd",
                    ),
                ),
                (
                    "address",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="address.address",
                    ),
                ),
                (
                    "crowds",
                    models.ManyToManyField(related_name="churches", to="person.crowd"),
                ),
            ],
            bases=("person.crowd",),
        ),
    ]
