# Generated by Django 4.2.7 on 2023-11-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0003_remove_crowd_address"),
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
        migrations.RemoveField(
            model_name="church",
            name="id",
        ),
        migrations.RemoveField(
            model_name="church",
            name="name",
        ),
        migrations.AddField(
            model_name="church",
            name="crowd_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="person.crowd",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="church",
            name="crowds",
            field=models.ManyToManyField(related_name="churches", to="person.crowd"),
        ),
    ]
